// This file is re-generated by kickzig when a record is added or removed.
// DO NOT EDIT THIS FILE.
const std = @import("std");
const testing = std.testing;

pub const contact = @import("src/contact.zig");
