/// This is the "edit" message.
/// This file was generated by kickzig when you added the "edit" message.
/// This file will be removed by kickzig when you remove the "edit" message.
/// KICKZIG TODO: Customize the "edit" message.
const std = @import("std");

// Message is the "edit" message.
pub const Message = struct {
    _allocator: std.mem.Allocator = undefined,
    _reinits: i32 = 0,

    // KICKZIG TODO:  Add your own Message fields and methods.

    pub fn deinit(self: *Message) void {
        self._reinits -= 1;
        if (self._reinits == 0) {
            self._allocator.destroy(self);
        }
    }

    pub fn reinit(self: *Message) void {
        self._reinits += 1;
    }
};

/// init constructs a new Message.
/// KICKZIG TODO: customize this constructor if needed.
pub fn init(allocator: std.mem.Allocator) !*Message {
    var message: *Message = try allocator.create(Message);
    message._allocator = allocator;
    message._reinits = 0;
    return message;
}
