/// This file is re-generated by kickzig when a screen is added or removed.
/// DO NOT EDIT THIS FILE.
const std = @import("std");
const testing = std.testing;

pub const initialize = @import("src/initialize.zig");
pub const fatal = @import("src/fatal.zig");

pub const add = @import("src/add.zig");
pub const edit = @import("src/edit.zig");
