/// This channel dispatches the "fatal" message.
/// The "fatal" message is only sent by the back-end to the front-end.
/// Any back-end messenger can send the "fatal" message to the back-end by calling send.
/// If the back-end sends a fatal message to the front end, then the front-end will initialize a gracefull shutdown of the entire app.
/// This file was generated by kickzig when you initialized the framework.
/// DO NOT EDIT THIS FILE.
const std = @import("std");

pub const _message_ = @import("message").fatal;

/// Behavior is call-backs and state.
/// .receiveFn is a call-back, a function that receives the message.
/// .self is the state required for the call-back. It is the implementor of the recieveFn.
pub const Behavior = struct {
    receiveFn: *const fn (self: *anyopaque, message: *_message_.Message) void,
    self: *anyopaque,
};

pub const Group = struct {
    allocator: std.mem.Allocator = undefined,
    members: std.AutoHashMap(*anyopaque, *Behavior),
    _sent: bool,
    _message: *_message_.Message,

    pub fn initBehavior(self: *Group) !*Behavior {
        return self.allocator.create(Behavior);
    }

    pub fn deinit(self: *Group) void {
        self.members.deinit();
        self.allocator.destroy(self);
    }

    pub fn subscribe(self: *Group, cb: *Behavior) !void {
        try self.members.put(cb.self, cb);
    }

    pub fn unsubscribe(self: *Group, caller: *anyopaque) bool {
        if (self.members.getEntry(caller)) |entry| {
            var cb: *Behavior = @ptrCast(entry.value_ptr.*);
            self.allocator.destroy(cb);
            return self.members.remove(caller);
        }
    }

    /// sendError dispatches the error in a message to the subscribers in Group.
    /// It takes control of the message and deinits it.
    /// It does not take control of err which is allocated on the stack.
    pub fn sendError(self: *Group, err: anyerror) void {
        if (self._sent) {
            return;
        }
        self._sent = true;
        var message: *_message_.Message = self._message;
        message.setError(err);
        dispatchDeinit(self.members, message);
    }

    fn dispatchNoThread(self: *Group, message: *_message_.Message) !void {
        dispatchDeinit(self.members, message);
    }
};

pub fn init(allocator: std.mem.Allocator) !*Group {
    var channel: *Group = try allocator.create(Group);
    channel.allocator = allocator;
    channel.members = std.AutoHashMap(*anyopaque, *Behavior).init(allocator);
    errdefer {
        allocator.destroy(channel);
    }
    channel._message = try _message_.init(allocator, error.Null);
    errdefer {
        channel.members.deinit();
        allocator.destroy(channel);
    }
    channel._sent = false;
    return channel;
}

fn dispatchDeinit(members: std.AutoHashMap(*anyopaque, *Behavior), message: *_message_.Message) void {
    defer message.deinit();
    var iterator = members.iterator();
    while (iterator.next()) |entry| {
        var behavior: *Behavior = entry.value_ptr.*;
        behavior.receiveFn(behavior.self, message);
    }
}
