/// This is the front-end's main menu data.
/// This file was generated by kickzig when you created this framework.
/// You are free to edit this file.
const ScreenTags = @import("framers").ScreenTags;

/// KICKZIG TODO:
// startup_screen_tag is the screen displayed at startup.
pub const startup_screen_tag: ScreenTags = .HelloWorld;

/// KICKZIG TODO:
/// if true, the main menu is displayed.
/// if false, the main menu is not displayed.
pub const show_main_menu: bool = true;

/// KICKZIG TODO:
/// sorted_main_menu_screen_tags is the sorted list of screens
///  that the user can access in the main menu.
pub const sorted_main_menu_screen_tags = [_]ScreenTags{
    .HelloWorld,
};

/// KICKZIG TODO:
/// if true, the dvui developer menu items are displayed in the main menu.
/// if false, the dvui developer menu items are not displayed in the main menu.
pub const show_developer_menu_items: bool = true;